//保存dataset 请求对象
const SET_USERNAME = 'SET_USERNAME'; //保存用户名
const SAVE_DATASET_KEYWORD = 'SAVE_DATASET_KEYWORD'; //dataset搜索关键字
const SAVE_TABLE_NAME = 'SAVE_TABLE_NAME';
const SAVE_FLOW_KEYWORD = 'SAVE_FLOW_KEYWORD'; //flow搜索关键字
const TREE_ITEM_ACTIVE = 'TREE_ITEM_ACTIVE'; //当前点击树状item
const SAVE_UPLOAD_DATA = 'SAVE_UPLOAD_DATA'; //模版上传选择的上传文件

const SAVE_FLOW_PROCESS = 'SAVE_FLOW_PROCESS'; //flow流程列表
const SAVE_FLOW_TASK = 'SAVE_FLOW_TASK'; //flow任务列表

const SAVE_MANUAL_PATH_DATA = 'SAVE_MANUAL_PATH_DATA'; //手动导入设置路径
const SAVE_SEARCH_VISIBLE = 'SAVE_SEARCH_VISIBLE';
const SAVE_SEARCH_ADVANCE = 'SAVE_SEARCH_ADVANCE';
const SAVE_PROCESS_SORT = 'SAVE_PROCESS_SORT';

const SAVE_SELECT_ITEM = 'SAVE_SELECT_ITEM'; //选择移动的项目

const SAVE_VIEW_NOTTABLE = 'SAVE_VIEW_NOTTABLE'; //保存不是表的连接
const SAVE_VIEW_TABLE = 'SAVE_VIEW_TABLE'; //保存表的连接

const SAVE_CHECKLIST = 'SAVE_CHECKLIST'; //添加数据
const SAVE_ISBUSINESS = 'SAVE_ISBUSINESS'; //是否是业务视图
const SAVE_ISBUSINESS_TITLE = 'SAVE_ISBUSINESS_TITLE'; //是否是业务视图标题
const ADD_THEMECHECKLIST = 'ADD_THEMECHECKLIST'; //添加表
const DEL_THEMECHECKLIST = 'DEL_THEMECHECKLIST'; //删除已选表
const ADD_HEADERNAV = 'ADD_HEADERNAV'; //header导航
const SAVE_SOURCEUSER = 'SAVE_SOURCEUSER'; //资源空间权限
const SAVE_SOURCETITLE = 'SAVE_SOURCETITLE'; //资源空间头部标题
const SAVE_FETCHROUTER = 'SAVE_FETCHROUTER';
const SET_LANGUAGE = 'SET_LANGUAGE';
const SELECT_ITEMS = 'SELECT_ITEMS'; //添加权限item
const DELET_ITEM = 'DELET_ITEM'; //删除权限item
const SET_EXPORT_LIST = 'SET_EXPORT_LIST'; //导出元数据表
const DELETE_EXPORT_LIST = 'DELETE_EXPORT_LIST'; //删除所选库下的表
const SET_EXPORT_DB_LIST = 'SET_EXPORT_DB_LIST'; //导出元数据库
const DELETE_EXPORT_DB_LIST = 'DELETE_EXPORT_DB_LIST'; //删除所选库下的库
const CLEAR_EXPORT_LIST = 'CLEAR_EXPORT_LIST';//清除所选表
const SAVE_BUSINESS_STATE = 'SAVE_BUSINESS_STATE'; //存储物理视图路由状态
const SET_TREE_DATA = 'SET_TREE_DATA'; //树状结构是否有数据
const BEGINREQUEST = 'BEGINREQUEST';  //树状结构开始请求
const SAVE_IMPORT_PRIVILEGE = 'SAVE_IMPORT_PRIVILEGE'; //导入权限
const SET_EXPORT_SEARCH = 'SET_EXPORT_SEARCH';//导出搜索
const SET_DATA_STATUS = 'SET_DATA_STATUS'; // 数据状态
const SET_TREE_LOADING = 'SET_TREE_LOADING';//树状图loading
const TREE_BUSINESS_LOADING = 'TREE_BUSINESS_LOADING';//物理视图loading
const SAVE_COLLECT_COUNT = 'SAVE_COLLECT_COUNT';//管理的表收藏的数据
const SET_FULL_LOADING = 'SET_FULL_LOADING';//设置全局的loading
const FULL_TREE_LOADING = 'FULL_TREE_LOADING';
const SAVE_ROUTER = 'SAVE_ROUTER';//判断导入返回路由
const SET_NAV_DATA = 'SET_NAV_DATA'; //设置导航链接
const SET_PRIVATE = 'SET_PRIVATE';//设置该表是否隐藏
const SET_PROPEDITPRIVILEGE = 'SET_PROPEDITPRIVILEGE';//非普通成员，项目管理员非自己项目的权限
const SET_SOURCELINK = 'SET_SOURCELINK'; //新建数据源
const SET_CREATETASK = 'SET_CREATETASK'; //新建任务第一步
const ADD_TABLES = 'ADD_TABLES'; //点击库请求库下的表
const SAVE_BLACKLIST = 'SAVE_BLACKLIST'; //黑名单
const GET_SAMPLE = 'GET_SAMPLE'; //判断生命周期
const SEARCH_TABLE = 'SEARCH_TABLE'; //黑名单搜索表
const CRON_VALUE = 'CRON_VALUE'; //cron最后生成值
const SHOW_CRON = 'SHOW_CRON'; //文字显示的cron
const CLOSE_DIALOG = 'CLOSE_DIALOG'; //关闭cron的dialog
const SELECT_TABLE = 'SELECT_TABLE'; //黑白名单已选择的表
const CLEAR_TABLE = 'CLEAR_TABLE'; //选择库后清除库下的表
const SET_EXPORT_TABLE_SOURCE = 'SET_EXPORT_TABLE_SOURCE'; //存放表和数据源的关系
const TEST_BLACKLIST = 'TEST_BLACKLIST'; //
const SAVE_SELECTLIST = 'SAVE_SELECTLIST';
const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS'; //设置首页搜索参数
const CHANGE_TABLE_TYPE_OPTS = 'CHANGE_TABLE_TYPE_OPTS'; // 左侧菜单过滤条件
const SET_MODEL_OPEN = 'SET_MODEL_OPEN'; // 存放树状图的展开和关闭
const SET_MANAGE_INFO = 'SET_MANAGE_INFO'; // 存放树状图的展开和关闭
const SET_USER_INFO = 'SET_USER_INFO'; // 存放用户信息，用来做权限判断
const SET_OWNER_TAB = 'SET_OWNER_TAB'; // 存放所属的表tab
const SET_NAV_VISIBLE = 'SET_NAV_VISIBLE'; // 存放导航显示与消失
const CLEAR_TIMEOUT = 'CLEAR_TIMEOUT'; // 存放导航显示与消失
const SOURCE_TYPE = 'SOURCE_TYPE'; // 搜索类型
const SAVE_VERSIONS = 'SAVE_VERSIONS'; //保存当前表的所有版本号
const TOGGLE_EDITING_STATUS = 'TOGGLE_EDITING_STATUS'; //切换编辑状态

export {
  SET_USERNAME,
  SAVE_DATASET_KEYWORD,
  SAVE_TABLE_NAME,
  SAVE_FLOW_KEYWORD,
  TREE_ITEM_ACTIVE,
  SAVE_UPLOAD_DATA,
  SAVE_FLOW_PROCESS,
  SAVE_FLOW_TASK,
  SAVE_MANUAL_PATH_DATA,
  SAVE_SEARCH_VISIBLE,
  SAVE_SEARCH_ADVANCE,
  SAVE_PROCESS_SORT,
  SAVE_SELECT_ITEM,
  SAVE_VIEW_NOTTABLE,
  SAVE_VIEW_TABLE,
  SAVE_CHECKLIST,
  SAVE_ISBUSINESS,
  SAVE_ISBUSINESS_TITLE,
  ADD_THEMECHECKLIST,
  DEL_THEMECHECKLIST,
  ADD_HEADERNAV,
  SAVE_SOURCEUSER,
  SAVE_SOURCETITLE,
  SAVE_FETCHROUTER,
  SET_LANGUAGE,
  SELECT_ITEMS,
  DELET_ITEM,
  SET_EXPORT_LIST,
  DELETE_EXPORT_LIST,
  SET_EXPORT_DB_LIST,
  DELETE_EXPORT_DB_LIST,
  CLEAR_EXPORT_LIST,
  SAVE_BUSINESS_STATE,
  SET_TREE_DATA,
  BEGINREQUEST,
  SAVE_IMPORT_PRIVILEGE,
  SET_EXPORT_SEARCH,
  SET_DATA_STATUS,
  SET_TREE_LOADING,
  TREE_BUSINESS_LOADING,
  SAVE_COLLECT_COUNT,
  SET_FULL_LOADING,
  FULL_TREE_LOADING,
  SAVE_ROUTER,
  SET_NAV_DATA,
  SET_PRIVATE,
  SET_PROPEDITPRIVILEGE,
  SET_SOURCELINK,
  SET_CREATETASK,
  ADD_TABLES,
  SAVE_BLACKLIST,
  GET_SAMPLE,
  SEARCH_TABLE,
  CRON_VALUE,
  CLOSE_DIALOG,
  SHOW_CRON,
  SELECT_TABLE,
  CLEAR_TABLE,
  SET_EXPORT_TABLE_SOURCE,
  TEST_BLACKLIST,
  SAVE_SELECTLIST,
  SET_SEARCH_PARAMS,
  CHANGE_TABLE_TYPE_OPTS,
  SET_MODEL_OPEN,
  SET_MANAGE_INFO,
  SET_USER_INFO,
  SET_OWNER_TAB,
  SET_NAV_VISIBLE,
  CLEAR_TIMEOUT,
  SOURCE_TYPE,
  SAVE_VERSIONS,
  TOGGLE_EDITING_STATUS
};
